### ISSUE TITLE
FindDbView does not check for an existing entity with the same name

### ISSUE THREAD

**Issue by aabiabdallah** [moqui/moqui-runtime#103]
The create transition in FindDbView does not check if an entity with the same name already exists. We had a production instance where the customer unknowingly created a DbView with a name matching that of an existing entity and moqui started behaving funny.

**Comment by jonesde** [comment]
Thank you Ayman. Those screens haven't seen much effort in a while and in addition to this there was a fix needed for EditDbView which wasn't working with the latest framework code. The changes are in commit 72f706b.

BTW, there is a replacement for the Data View screens in the tools app using view entities based on DataDocument definitions, with a decent screen for creating/editing them. These go way beyond the DbViewEntity based stuff allowing multiple relationship hops to join in fields (as opposed to one in the Data View screens), a much smoother UI, ability to add conditions, and more. It has a generic Find screen (with selectable columns, find options dialog, etc) and the ability to export CSV and JSON.

These are available in the Data Document section of the System app, and being more end-user oriented (for experienced/pro users though) it is also available in the POPC ERP and HiveMind PM apps as a custom report builder and a separate customer report view screen with more open permissions and per-report configuration for which user groups can see it.
