### ISSUE TITLE
Vuet AutoScreen unable to Get Forms XML

### ISSUE THREAD

**Issue by donniexyz** [moqui/moqui-runtime#108]
To reproduce:
1. goto https://demo.moqui.org/vapps/tools/AutoScreen/AutoFind?aen=mantle.account.method.PaymentGatewayConfig

2. click Get Forms XML

3. on screen message pop up: Form data saved

On Web Developer:
1. CombinedVuet.min.js:45 **m-form no response or non-JSON response: {"location":null}**
handleResponse @ CombinedVuet.min.js:45
2. moqui server did return the xml form.

Its working fine on /apps.

**Comment by jonesde** [comment]
This is fixed for the AutoFind, AutoEditMaster, and AutoEditDetail screens in commit 9f4c291.
