### ISSUE TITLE
How to implement jackrabbit  in moqui framework

### ISSUE THREAD

**Issue by hexd-moshi** [moqui/moqui-runtime#114]
Here is my steps:
1. put jackrabbit-standalone-2.11.3.jar into folder runtime/jackrabbit
2. update MoquiDefaultConf.xml, 
		<tool-factory class="org.moqui.impl.tools.JackrabbitRunToolFactory" init-priority="40" disabled="false"/>

But I cannot start up jackrabbit, may I know how to setup it ? thanks

**Comment by shendepu** [comment]
Please provide more detail information or error message. 

The basic steps of implementing jackrabbit are: 
1. check the version of jackrabbit in `classes/jackrabbit_moqui.properties`
2. put the jackrabbit-standalone-`version`.jar in `runtime/jackrabbit`
3. add below conf in `MoquiConf.xml` of your component
```
    <repository-list>
        <!-- requires 'org.apache.jackrabbit:jackrabbit-jcr-rmi' in the classpath: -->
        <repository name="main" workspace="default" username="admin" password="admin">
            <init-param name="org.apache.jackrabbit.repository.uri" value="http://localhost:8081/rmi"/></repository>
    </repository-list>
```

**Comment by hexd-moshi** [comment]
Follow your steps:
1. check the jackrabbit_moqui.properties, moqui.jackrabbit_jar = jackrabbit-standalone-2.11.3.jar
2. put jackrabbit-standalone-2.11.3.jar into folder runtime/jackrabbit
3. update MoquiDefaultConf.xml 
<tool-factory class="org.moqui.impl.tools.JackrabbitRunToolFactory" init-priority="40" disabled="false"/>
4. update MoquiConf.xml in my component
<repository-list>
        <repository name="main" workspace="default" username="admin" password="admin">
            <init-param name="org.apache.jackrabbit.repository.uri" value="http://localhost:8081/rmi"/></repository>
    </repository-list>

The error message as below:
ERROR         main             o.m.i.c.ResourceFacadeImpl Could not find JCR RepositoryFactory for
 repository main using parameters: [org.apache.jackrabbit.repository.uri:http://localhost:8081/rmi]

**Comment by shendepu** [comment]
OK, I know the problem.

There is one comment at https://github.com/moqui/moqui-framework/blob/master/framework/src/main/resources/MoquiDefaultConf.xml#L631 about using jackrabbit that you need to have the `jackrabbit-jcr-rmi` jar. You may add 
```
compile 'org.apache.jackrabbit:jackrabbit-jcr-rmi:2.12.1' // Apache 2.0
```
in `build.gradle` in your component.

By the way, you don't need to change `MoquiDefaultConf`. You may simply add 
```
<tool-factory class="org.moqui.impl.tools.JackrabbitRunToolFactory" disabled="false"/>
```
in `MoquiConf.xml` in your component.

**Comment by hexd-moshi** [comment]
It is Ok now, thanks
