### ISSUE TITLE
Download file not work

### ISSUE THREAD

**Issue by betwowt** [moqui/moqui-runtime#118]
https://demo.moqui.org/apps/example/Example/EditExampleContent?exampleId=100153
can download file
https://demo.moqui.org/vapps/example/Example/EditExampleContent?exampleId=100153
can't download file

**Comment by jonesde** [comment]
This is fixed in commit d9c7745 in the example component. The issue is not in moqui-runtime but rather in the ExampleContent screen where the download transition needs to be marked as read-only.
