### ISSUE TITLE
Testing APIs with Swagger UI

### ISSUE THREAD

**Issue by samhamilton** [moqui/moqui-runtime#13]
Hi David, 

Just found that if you are trying to test out an API on the demo server then you get a mixed content error message and it wont process:

```
swagger-ui.min.js:10 Mixed Content: The page at 'https://demo.moqui.org/assets/lib/swagger-ui/index.html?url=https://demo.moqui.org/rest/service.swagger/example#!/examples/post_examples' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://demo.moqui.org:443/rest/s1/example/examples'. This request has been blocked; the content must be served over HTTPS.
```

Thanks
Sam

**Comment by jonesde** [comment]
Looked into this briefly: happens because the domain name has a port but no protocol and Swagger UI seems to default to http, so an explicit protocol needs to be added.

**Comment by jonesde** [comment]
The main changes for this are in moqui-framework, and also the commit referenced above in moqui-runtime. Swagger is annoying in that the host field needs to have the port, but the schemes allowed are listed separately and it isn't smart enough to pick https when and https port is used. Now the Swagger generated always has one scheme to match the port/etc in the host and it seems to work fine on demo.moqui.org.

Note that the version now on demo.moqui.org has the new JS/CSS libraries in place, was an interesting test of that too. In many ways it looks way better, a few improvements as part of that bigger effort.
