### ISSUE TITLE
The Qz-tray component is not working for the production mode

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-runtime#131]
I config the production mode as flows
<default-property name="instance_purpose" value="production"/>

and the Qz component is not displayed in the WebrootVue.vuet.ftl <component :is="qzVue" ref="qzVue"></component>

**Comment by jonesde** [comment]
This is brand new but seems to be working well. What steps did you take beyond a basic Moqui setup to enable and such? The main thing to enable it period is to set the 'qz.print.enabled' User Preference (for a single user or group) to the value "true" (see vapps.xml, conditional include of various JS files).

**Comment by WillWei1983** [comment]
sorry,My input is missing,Yes, I have set the qz.print.enabled' to be true, it works when

**Comment by WillWei1983** [comment]
sorry that my input is missing the info. I have setup the qz.print.enabled' , and it works when the instance_purpose is dev, but it is not working when the instance_purpose is production

**Comment by jonesde** [comment]
Yes, there was an issue with load order when instancePurpose == 'production'. This is fixed in commit 707fbef.
