### ISSUE TITLE
Is the macro-template support the vuet type?

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-runtime#132]
I make a CustomScreenMacros.vuet.ftl and config it like this `<macro-template type="html,vuet" location="template/screen-macro/CustomScreenMacros.vuet.ftl"/>` but it doesn't take effected. after checking the xsd `<xs:attribute name="type" type="xs:string" use="required">
            <xs:annotation><xs:documentation>
                Can be anything. Default supported values include: text, html, xsl-fo, xml, and csv.
            </xs:documentation></xs:annotation>
        </xs:attribute>`
it is not support the vuet mode yet?

**Comment by jonesde** [comment]
In the Moqui Conf XML file the macro-template@type attribute cannot have a comma separated list of types like you have here (ie type="html,vuet"), it can only be a single type.
