### ISSUE TITLE
The default expire-time-idle in MoquiDevConf should be bigger than 60

### ISSUE THREAD

**Issue by lightning-pro** [moqui/moqui-runtime#139]
In the MoquiDevConf.xml 
`<cache name="entity.data.feed.info" expire-time-idle="30"/>`

and there is a checking in the EntityDataFeed.rebuildDataFeedEntityInfo()
if (System.currentTimeMillis() < (lastRebuildTime + 60000)) return
When the cache is expired and rebuildDataFeedEntityInfo is excuted, it will just return and the document data won't be indexed

**Comment by jonesde** [comment]
Thanks for reporting this, I missed it long ago but was recently looking into this after noticing in a dev instance... and it should only be an issue with the dev configuration. There are some changes in moqui-framework commit ba199ea that should address this.
