### ISSUE TITLE
DateTimePicker month display issues

### ISSUE THREAD

**Issue by corncore** [moqui/moqui-runtime#22]
selected a month in the DateTimePicker , month display is incorrect

**Comment by jonesde** [comment]
Which version of Moqui? Any hints about what is incorrect, i.e. what you actually saw and how it is different from what you expected to see?

**Comment by jonesde** [comment]
More information is needed as I'm not able to reproduce this. In recent changes to moqui-runtime for JS/etc libraries a new datetimepicker is used, but I don't see anything wrong with the month display.
