### ISSUE TITLE
Datetime picker not working correctly in modal dialog when using custom format

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-runtime#40]
The datetime picker in modal dialog works correctly, when custom format is not applied. When I set the format to custom, it stops working.

**This one is not working:**

![image](https://cloud.githubusercontent.com/assets/14863763/17005623/8a87343e-4edb-11e6-8874-515512ad1877.png)

![image](https://cloud.githubusercontent.com/assets/14863763/17005641/9ee9478c-4edb-11e6-97a3-1dd289361175.png)

**This one is working:** Format not defined.

![image](https://cloud.githubusercontent.com/assets/14863763/17005585/686a535e-4edb-11e6-985a-a0a575e269fb.png)

![image](https://cloud.githubusercontent.com/assets/14863763/17005856/f8cb7774-4edc-11e6-87b9-28e716f677ac.png)

**Comment by jonesde** [comment]
My guess is the JS date/time widget doesn't like the format string. You can view source to see what it is translated to, and my guess is there is an error on the JS console log in your browser.

This seems related to a more general issue:

https://github.com/moqui/moqui-framework/issues/49

**Comment by chunlinyao** [comment]
Found the reason, maybe a bug in datetimepicker, `parseInputValue` called before `initFormatting`, have a workaround.

**Comment by mrovnanik** [comment]
I cannot reproduce the behavior, but I have used this custom format in datetimepicker maybe a month ago. I am pretty sure, because I was testing manual input (by typing directly into the textbox) of date on the very same screen.

**Comment by chunlinyao** [comment]
It only occur when a string `defaultDate` and custom `format` set together.

**Comment by mrovnanik** [comment]
I see. Now it's working, I pulled your commit. Thanks very much, I am having a business meeting in an hour, this helps, because I can show the whole application right now.
