### ISSUE TITLE
Field focus lost when using keyboard topick in dropdown (in modal)

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-runtime#42]
This occurs in dialog, opened as modal (dialog).

After I fill the value in the first dropdown using keyboard (search party, then hit Enter to confirm the selection), the field focus is lost (I would expect the focus to jump to the next field on the dialog). But when I hit TAB, the fields on the parent form are focused instead (starting with icon as seen on the screenshot).

If I want to get back on the next field in the dialog, I have to TAB over all items on the parent. This makes use of keyboard quite ineffective.

Can I set the tab index of the fields somehow?

![image](https://cloud.githubusercontent.com/assets/14863763/17302566/1ca6d384-581d-11e6-9023-3d5f381a8571.png)

![image](https://cloud.githubusercontent.com/assets/14863763/17302570/200396de-581d-11e6-8ae9-65eef3632a72.png)

![image](https://cloud.githubusercontent.com/assets/14863763/17302576/25d101c8-581d-11e6-8741-de10f4b3e7e2.png)

**Comment by jonesde** [comment]
I tried this (using the latest code) in the New Invoice modal in the FindInvoice screen in POP Commerce and was unable to reproduce this. Selecting an item in the drop-down with the keyboard, pressing enter to select, and then pressing tab to move to the next field works fine as does pressing shift-tab to move back to the previous field.

Is there a screen in one of the applications (like System, Tools, HiveMind, POP Commerce) where I can reproduce what you are seeing? Did I miss something in what I tried, i.e. you are seeing an issue doing something different?

**Comment by jonesde** [comment]
BTW, which browser are you using? I've noticed dramatically different tab behavior in different browsers, and in some browsers (like Safari) there are preference settings that change this too.

**Comment by jonesde** [comment]
Looking at this more, testing in Firefox and with different tabbing settings in Safari, it looks like the issue is specific to Select2 with a search box and happens regardless of whether it is in a modal. What to do about it is another question (hopefully some solution in the Select2 world).

**Comment by mrovnanik** [comment]
I am using Chrome. David, I can send you a link to my application and login credentials, so that you can use it right there where I experienced it.

**Comment by jonesde** [comment]
I added a Select2 hack in commit #565dc89 that resolves this in my local tests. Let me know if it works for you, and if so I think this issue can be closed.

**Comment by jonesde** [comment]
Have you had a chance to look at this @mrovnanik ? From my tests I think this issue can be closed.

**Comment by mrovnanik** [comment]
Sorry for the delay, yes, the behavior is correct right now. Thanks David.
