### ISSUE TITLE
DefaultScreenMacro.xsl-fo.ftl and DefaultScreenMacros.text.ftl out-of-date 

### ISSUE THREAD

**Issue by bizartifact** [moqui/moqui-runtime#46]
The code for <#macro "form-single"> is out-of-date:

<#assign formNode = sri.getFtlFormNode(.node["@name"])>
${sri.setSingleFormMapInContext(formNode)}

possible replacement with:

<#assign formInstance = sri.getFormInstance(.node["@name"])>
<#assign formNode = formInstance.getFtlFormNode()>
${sri.pushSingleFormMapContext(formNode)}

**Comment by jonesde** [comment]
The getFtlFormNode() method does the same thing internally. Getting a form instance explicitly is only needed when other things in the form instance are needed and are not needed for form-single. In both of the files you mentioned in the issue description getFormInstance() is used in the form-list macro.

**Comment by igorgallingani** [comment]
I'm Sorry, I mean from setSingleFormMapInContext to pushSingleFormMapContext.

**Comment by jonesde** [comment]
Thank you for pointing that out, I missed it before. This should be fixed in commit #760e932. Please test in your scenario and close this if it is now working for you.

I also tested the general rendering to text and xsl-fo for a couple of screens with form-single and fixed some other issues.
