### ISSUE TITLE
No signature of method: org.moqui.impl.service.ServiceFacadeImpl.getServiceJobRunner() is applicable for argument types: () values: [] Possible solutions: getServiceRunner(java.lang.String)

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-runtime#51]
When opening Service Jobs from Server Admin ...

![image](https://cloud.githubusercontent.com/assets/14863763/18604431/d49ad8fe-7c7c-11e6-9b7b-86b6f0a96835.png)

... the application returns an error:

Error rendering screen [component://tools/screen/System/ServiceJob/Jobs/ServiceJobList.xml]: groovy.lang.MissingMethodException: No signature of method: org.moqui.impl.service.ServiceFacadeImpl.getServiceJobRunner() is applicable for argument types: () values: [] Possible solutions: getServiceRunner(java.lang.String)

![image](https://cloud.githubusercontent.com/assets/14863763/18604427/c8fd2272-7c7c-11e6-8bf9-a764f484d702.png)

**Comment by jonesde** [comment]
I'll look into this, could very well be a bug!

**Comment by jonesde** [comment]
Thank you, I mistakenly cleaned out that 'unused' method in a commit not long back. This is fixed in commit #d01f404 and in moqui-framework commit #524ce2e.
