### ISSUE TITLE
Issue running Moqui with standalone MySQL DB 5.7.11

### ISSUE THREAD

**Issue by aabiabdallah** [moqui/moqui-runtime#6]
I downloaded the new Moqui 1.6.1 framework and executed the gradle load and gradle run commands, everything worked splendidly. Next I added the MySQL JDBC driver to runtime/lib and configured the entity-facade.datasource in MoquiDevConf.xml as follows:

`<datasource group-name="transactional" database-conf-name="mysql" schema-name="" startup-add-missing="true">
    <inline-jdbc jdbc-uri="jdbc:mysql://127.0.0.1:3306/moqui161?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8"
                 jdbc-username="moqui" 
                 jdbc-password="moqui" 
                 pool-minsize="2" 
                 pool-maxsize="50" />
</datasource>`

I then ran gradle load again and encountered the following error:

--- 17:25:01.816 [           main] ERROR       org.moqui.impl.entity.EntityDbMeta
 SQL Exception while executing the following SQL [CREATE TABLE EMAIL_MESSAGE (EMAIL_MESSAGE_ID VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, ROOT_EMAIL_MESSAGE_ID VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci, PARENT_EMAIL_MESSAGE_ID VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci, STATUS_ID VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci, EMAIL_TYPE_ENUM_ID VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci, SENT_DATE DATETIME(3), RECEIVED_DATE DATETIME(3), SUBJECT VARCHAR(4095) CHARACTER SET utf8 COLLATE utf8_general_ci, BODY LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci, NOTE VARCHAR(4095) CHARACTER SET utf8 COLLATE utf8_general_ci, HEADERS_STRING LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci, FROM_ADDRESS VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci, TO_ADDRESSES VARCHAR(4095) CHARACTER SET utf8 COLLATE utf8_general_ci, CC_ADDRESSES VARCHAR(4095) CHARACTER SET utf8 COLLATE utf8_general_ci, BCC_ADDRESSES VARCHAR(4095) CHARACTER SET utf8 COLLATE utf8_general_ci, CONTENT_TYPE VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci, MESSAGE_ID VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci, FROM_USER_ID VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci, TO_USER_ID VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci, EMAIL_TEMPLATE_ID VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci, EMAIL_SERVER_ID VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci, LAST_UPDATED_STAMP DATETIME(3), CONSTRAINT PK_EMAIL_MESSAGE PRIMARY KEY (EMAIL_MESSAGE_ID)) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
--- 17:25:01.816 [           main] WARN  moqui.impl.context.TransactionFacadeImpl
 Rollback only not set on current transaction, status is STATUS_NO_TRANSACTION
--- 17:25:01.817 [           main] INFO        org.moqui.impl.entity.EntityDbMeta
 Created table [EMAIL_MESSAGE] for entity [moqui.basic.email.EmailMessage]

The only way I was able to proceed was to override the database-list.database configuration in MoquiDevConf.xml as follows:

`<database name="mysql" join-style="ansi-no-parenthesis" offset-style="limit"
        table-engine="InnoDB" character-set="utf8" collate="utf8_general_ci"
        default-isolation-level="ReadCommitted" default-jdbc-driver="com.mysql.jdbc.Driver"
        default-xa-ds-class="com.mysql.jdbc.jdbc2.optional.MysqlXADataSource"
        default-test-query="SELECT 1">
    <database-type type="text-long" sql-type="TEXT"/>
</database>`

**Comment by jonesde** [comment]
There is discussion about this in another issue. You can update to the latest source from trunk, or just modify the EmailMessage entity definition in the framework/entity/BasicEntities.xml file (try removing the note field, changing the subject to text-medium).

**Comment by jonesde** [comment]
BTW, these issues should go in the moqui-framework repository instead of here (the moqui-runtime one). Most framework issues apply to the code/etc there as opposed to the runtime artifacts here which are mostly UI.
