### ISSUE TITLE
header-field.@title is being ignored in single forms

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-runtime#65]
The field.header-field.@title attribute is being ignored inside form-single forms, using the default field.@name string instead.
According to pull request https://github.com/moqui/HiveMind/pull/24 , this is not be the correct behavior and should be fixed.
Example of this behavior is in the "AddUserAssignForm" (when clicking on "Add User Assignment"), visible at https://demo.moqui.org/apps/hmadmin/Project/EditUsers?rootWorkEffortId=HM . Two titles have an ignored header-field.@title attribute:

- expectationEnumId: title should be "Expectation" but is "Expectation Enum Id"
- emplPositionClassId: title should be "Position Class" but is "Empl Position Class ID".

**Comment by jonesde** [comment]
I misunderstood your previous issue in HiveMind. The header-field element is ignored in form-single (it is ONLY used in form-list), so @title must be on default-field or conditional-field. In other words there was an issue in the screen which is fixed in HiveMind commit #0e4cd25.
