### ISSUE TITLE
Issue running Moqui with standalone MySQL DB 5.5.42

### ISSUE THREAD

**Issue by aabiabdallah** [moqui/moqui-runtime#7]
I downloaded the new Moqui 1.6.1 framework and executed the gradle load and gradle run commands, everything worked splendidly. Next I added the MySQL JDBC driver to runtime/lib and configured the entity-facade.datasource in MoquiDevConf.xml as follows:

`<datasource group-name="transactional" database-conf-name="mysql" schema-name="" startup-add-missing="true"> <inline-jdbc jdbc-uri="jdbc:mysql://127.0.0.1:3306/moqui161?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8" jdbc-username="moqui" jdbc-password="moqui" pool-minsize="2" pool-maxsize="50" /> </datasource>`

I then ran gradle load again and encountered the following error on most of the tables:

--- 17:54:40.992 [           main] ERROR       org.moqui.impl.entity.EntityDbMeta
 SQL Exception while executing the following SQL [CREATE TABLE DATA_SOURCE (DATA_SOURCE_ID VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, DATA_SOURCE_TYPE_ENUM_ID VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci, DESCRIPTION VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci, LAST_UPDATED_STAMP DATETIME(3), CONSTRAINT PK_DATA_SOURCE PRIMARY KEY (DATA_SOURCE_ID)) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(3), CONSTRAINT PK_DATA_SOURCE PRIMARY KEY (DATA_SOURCE_ID)) ENGINE InnoDB CHARA' at line 1

This seems to be due to the following configuration:

`<database-type type="date-time" sql-type="DATETIME(3)"/>`

The only way I was able to move forward was to upgrade to MySQL 5.7.11. What is the minimum MySQL version that Moqui supports?

**Comment by jonesde** [comment]
Yes, unfortunately with newer versions of MySQL is you want milliseconds with DATETIME values (which Moqui needs) then you now have to use DATETIME(3) and it wasn't supported in older versions.

If you want to use an older version of MySQL just change the configuration (either in the MoquiDefaultConf.xml file, or preferably using an override with the same XML elements in your runtime Moqui Conf XML file).

**Comment by jonesde** [comment]
BTW, I see you are using the non-XA configuration for MySQL. I'd recommend using the xa-properties variation (see the current framework/src/main/resources/MoquiDefaultConf.xml file, line 314).
