### ISSUE TITLE
Search in Form-list not working as expected after elements have been put outside table element

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-runtime#78]
I noticed a change in behavior based on change in DefaultScreenMacros.html.ftl some time ago. Originally, the form-list macro rendered individual elements inside Table class. Then, after changing the macro  (<#-- all form elements outside table element and referred to with input/etc.@form attribute for proper HTML --> https://github.com/moqui/moqui-runtime/commit/50b9fbd5dcc292051c99b6f0936408ec055e5db0), the **search** feature stopped working (I am using Chrome on Windows 10).

Here are the screenshots to showcase the change in the HTML code being generated before and after:

This is how it looked before the change:
![header_inside_table](https://cloud.githubusercontent.com/assets/14863763/23254486/88956c30-f9b8-11e6-8cbc-580bc62b8279.png)

This is after the change:
![header_outside_table](https://cloud.githubusercontent.com/assets/14863763/23254490/8b7de2c4-f9b8-11e6-9427-45611e6e97ce.png)

There is a workaround to it. Just set header-dialog to true, then it starts working.

**Comment by jonesde** [comment]
How do I reproduce this? I ask because there are OOTB screens where this works fine, such as:

http://localhost:8080/apps/system/ArtifactHitBins

Which version of moqui-framework/-runtime are you using?

**Comment by mrovnanik** [comment]
Version 2.0.0. In my case, it's the newest code I downloaded today.

Sorry David, it was my fault. I had custom FTL macros used for that screen. And there was the "text-find" macro which rendered the field differently. It lacked the owner_form definition.

![comparing_headerfields](https://cloud.githubusercontent.com/assets/14863763/23258717/be392c08-f9c9-11e6-99b9-10e31b326cca.png)

On the left, there is the correct macro used, on right my forgotten one.
