### ISSUE TITLE
vuejs display menu different than html mode

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-runtime#80]
If a screen use <subscreens-acitve/> as decorator of subscreens, it will not listed in header menus, but in vuejs mode, it will listed in menu.

**Comment by jonesde** [comment]
That is correct. In the nav bar under vapps.xml the logic is slightly different than the navbar under apps.xml. I like the one under vapps.xml better personally, but haven't decided yet if it is worth it to change the menu in apps.xml to work the same way.
