### ISSUE TITLE
When form-list has a transition with some required field, search field in header dialog also become required.

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-runtime#90]
header-field also use `getFieldValidationClasses`, which got same result as field in body.

**Comment by jonesde** [comment]
I haven't run into this in any of the screens I've worked on as usually a form-list is display only with more complex find options (header fields) or is for updating records but rarely both.

This is a tricky one to fix, my initial thought on it is to set a global in the FTL macros (html and vuet) when in the header form (in the header row or in the header dialog) and then look for that in every form field macro to ignore or remove the required class. This is a fair bit of work, and is messy, but may be the only way given how the FTL form field macros currently work.

**Comment by chunlinyao** [comment]
If we want `getFieldValidationClasses` return a different result, we can pass a parameter to it or call it from a different form instance or change state of form instance. Pass parameter require change each form field macros. how about use a derived form instance when render head fields?

**Comment by jonesde** [comment]
This is fixed in a set of changes merged two days ago (Friday). The fix involved moving the automatically set validate-* attributes from the field element to the field sub-elements (default-field, etc).
