### ISSUE TITLE
Error in Tools component - EntityList.xml file - Find link

### ISSUE THREAD

**Issue by igorgallingani** [moqui/moqui-runtime#97]
At row 53, change parameter-map="[selectedEntity:entityName]" with parameter-map="[selectedEntity:fullEntityName]"

**Comment by aabiabdallah** [comment]
I personally encountered this when I have 2 entities, from 2 different components, with the same name.

**Comment by jonesde** [comment]
I made this change in commit #a95c475.

Supporting the same entity name in different packages hasn't been well tested, as I've mentioned elsewhere. Is this the only issue you've run into with that? If so I'm pleasantly surprised. :)
